[build]
  command = "npm install && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"

[context.production.environment]
  NETLIFY_DEPLOY_PREVIEWS = "false"